[Log]
Environment = "development" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[Server]
Host = "zkevm-pool-manager-001"
Port = 8545
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 500
EnableHttpLog = true
BatchRequestsEnabled = false
BatchRequestsLimit = 20

[DB]
User = "pool_manager_user"
Password = "redacted"
Name = "pool_manager_db"
Host = "localhost"
Port = "33202"
EnableLog = false
MaxConns = 200

[Sender]
SequencerURL = "http://127.0.0.1:33205"
ResendTxsCheckInterval = "1s"
Workers = 5
QueueSize = 25

[Monitor]
L2NodeURL = "http://127.0.0.1:33211"
Workers = 5
QueueSize = 25
RetryWaitInterval = "3s"
InitialWaitInterval = "1s"
TxLifeTimeMax = "300s"